### ISSUE TITLE
Change in behaviour. Urgent.

### ISSUE THREAD

**Issue by rivington101** [googleads/googleads-consent-sdk-ios#42]
We have an app that has used the SDK since May 18 there have been no changes to our EU consent implementation.  The current version of the app has been on the App Store for 3 months.
In the last week the consent form appears on almost every launch.
The only way this can happen is that inEEAOrUnkown is true followed by consent status being UNKOWN.
Has something changed with Google EU Consent status server?

**Comment by stowy** [comment]
We're aware of this issue and we're working to resolve it. I'll update you
when a solution is pending. The reason is because of changes in the Ad
providers list is triggering a new consent required, but the changes are
small changes occurring regularly which triggers the new consent flow more
often.

**Comment by mechmatt01** [comment]
Has there been a fix to this?

**Comment by rivington101** [comment]
It stopped doing it a few days after stowy replied.  So seems to be fixed
Now that the Californian privacy is coming into force will Google be updating this SDK?
